name: Test If Build
on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  test-popup-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Popup
        run: make build-popup

  test-options-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Options
        run: make build-options

  test-extension-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build extension
        run: make build-ext
